credentials:
  usernames:
    anotheruser:
      name: Another User
      password: 16472b57e17a8a0eafd5d6811cf5b182f6b4e2812e322d5fc33b0d1f19fb5832
    yourusername:
      name: Your Name
      password: e3c652f0ba0b4801205814f8b6bc49672c4c74e25b497770bb89b22cdeb4e951

cookie:
  name: yourcookie
  key: yourcookiekey
  expiry_days: 30
